### ISSUE TITLE
Doing something wrong? (Could not convert Foo.class to NMS class)

### ISSUE THREAD

**Issue by SignorPollito** [GamerCoder215/MobChip#21]
### Bug Type

Console Errors

### Description

Hi, I'm having a problem with MobChip library.

I'm getting an exception when trying to use the Player class in the PathfinderAvoidEntity.
https://imgur.com/a/0jouAJo

I'm I using the wrong class for the Player or is there a problem?
This is the line of code:
`BukkitBrain.getBrain(entity).getTargetAI().put(new PathfinderAvoidEntity<>(entity, Player.class, 5f, 1.5), 0);`

### Expected Behavior

Pathfinder should make the entity avoid Players without exceptions when adding it.

### Actual Behavior

An exception is thrown when trying to adding the Pathfinder.

**Comment by SignorPollito** [comment]
Problem solved using HumanEntity class instead of Player's one.

**Comment by GamerCoder215** [comment]
Will update the BiMap to properly use this. Thanks for commenting your solution!
