### ISSUE TITLE
Add avoidPredicate & predicateOnAvoidEntity to PathfinderAvoidEntity

### ISSUE THREAD

**Issue by aematsubara** [GamerCoder215/MobChip#31]
### Feature Type

Other

### Description of Feature

Hi! In the AvoidEntityGoal/PathfinderGoalAvoidTarget goal there are 2 predicates, one for the entity to be avoided and one for the entity avoiding (as shown [here](https://nms.screamingsandals.org/1.19.3/net/minecraft/world/entity/ai/goal/AvoidEntityGoal.html)) which are not present in the current version of MobChip and can be quite useful; for example, to avoid an entity that has a particular metadata. Hopefully you can add it! :)

**Comment by GamerCoder215** [comment]
That sounds like a good idea! I'll mark it as an addition for v1.7.2.

**Comment by GamerCoder215** [comment]
Draft is in `[8ea2c5e](https://github.com/GamerCoder215/MobChip/commit/8ea2c5e43c6a31971457e41f8a9284ec7292d683)`.

Will test soon, closing this issue now.
