### ISSUE TITLE
BukkitCreatureBehavior cannot be cast to FrogBehavior

### ISSUE THREAD

**Issue by grahhnt** [GamerCoder215/MobChip#72]
### Bug Type

Other Unexpected Behavior

### MobChip Version

1.9.0

### Server Version

Spigot 1.19.4

### Description

BukkitCreatureBehavior cannot be cast to FrogBehavior

### Expected Behavior

To be able to cast BukkitCreatureBehavior to FrogBehavior

### Actual Behavior

ClassCastException

**Comment by GamerCoder215** [comment]
An issue with behavior fetching reflection. Will work on a fix for v1.9.0.
