### ISSUE TITLE
PathfinderAvoidEntity API mistake

### ISSUE THREAD

**Issue by ShaneBeee** [GamerCoder215/MobChip#79]
### Bug Type

Compatibility Issues

### MobChip Version

1.9.0

### Server Version

n/a

### Description

I noticed the walk/sprint mods are backwards in the API:
<img width="1232" alt="Screenshot 2023-07-09 at 6 30 27 PM" src="https://github.com/GamerCoder215/MobChip/assets/20008482/112fba41-cbd7-4ac1-851b-a384101bfd19">

### Expected Behavior

not be backwards ;)

### Actual Behavior

backwards

**Comment by GamerCoder215** [comment]
Thanks for catching that!
