### ISSUE TITLE
Jitpack not working

### ISSUE THREAD

**Issue by Tom18314** [GamerCoder215/MobChip#85]
### Bug Type

Console Errors

### MobChip Version

1.9.1

### Server Version

1.20.1

### Description

Cant use jitpack to use API

![image](https://github.com/GamerCoder215/MobChip/assets/72739475/5c8f5e9e-02ef-4cb5-926a-410e1f5c438c)

### Expected Behavior

-_-

### Actual Behavior

Jitpack: status: error

**Comment by GamerCoder215** [comment]
JitPack (for some reason) won't build MobChip with JDK 17. I have no control over how JitPack builds repositories (because this is different from JitCI), so I cannot fix it.

Please use the [CodeMC Dependency Format](https://github.com/GamerCoder215/MobChip#installation).
