### ISSUE TITLE
moveTo not function properly

### ISSUE THREAD

**Issue by DarkSnakeX** [GamerCoder215/MobChip#87]
### Bug Type

Other Unexpected Behavior

### MobChip Version

1.9.2

### Server Version

1.19.3

### Description

When updating to this new version from 1.9.1 to 1.9.2 the function moveTo doesn't work as intended. 

### Expected Behavior

When using the function on a mob, I expect the mob to go to that location.

### Actual Behavior

It doesn't do it anymore. The mob freezes for like a milisecond and doesn't go there.

### Additional Information

Using Spigot 1.19.3

**Comment by GamerCoder215** [comment]
Can you show me your code? `moveTo` isn't relative but `naturalMoveTo` is. Did it work pre-1.9.1?

**Comment by DarkSnakeX** [comment]
Yes, it worked in 1.9.1
Here is the code:
`EntityBrain brain = BukkitBrain.getBrain(villager);
            EntityController controller = brain.getController();
            controller.moveTo(location, velocidad);
            controller.lookAt(location);`

**Comment by GamerCoder215** [comment]
> Yes, it worked in 1.9.1 Here is the code: `EntityBrain brain = BukkitBrain.getBrain(villager); EntityController controller = brain.getController(); controller.moveTo(location, 1); controller.lookAt(location);`

Is `location` a relative Location?

**Comment by DarkSnakeX** [comment]
location its from org.bukkit.Location;
Location location = event.getPlayer().getLocation();

**Comment by GamerCoder215** [comment]
Reverted in e174de1.
